9 Numpy

Generate matrices A, with random Gaussian entries, B, a Toeplitz matrix, where A ∈ R
n×m and B ∈ R
m×m,
for n = 200, m = 500.


In [17]:
import numpy as np
import scipy.linalg as sc
A = np.random.normal(0,1,(200,500))
B = sc.toeplitz(np.random.random(500))

print("A: " , A)
print ("B: " , B)

A:  [[ 0.59720374 -0.84989052  1.38676453 ... -1.36996552 -0.47526873
  -1.01920476]
 [-1.96902038  2.03788993  0.51659554 ... -2.02457587 -0.40219918
  -1.50813062]
 [-0.23847588  0.2335557  -0.78019272 ... -1.17969313  0.04056677
  -0.34643052]
 ...
 [ 1.14246452 -0.10022933 -0.66999693 ...  0.73383407  1.44510365
  -0.12838335]
 [ 0.99647438 -0.35006616  0.05811255 ...  0.82097411 -1.2463434
  -0.92116056]
 [ 0.76903313 -0.48521716  0.5361304  ... -1.93862668 -0.85862282
   0.33886486]]
B:  [[0.67296452 0.31920088 0.63920299 ... 0.30167372 0.74633885 0.95003145]
 [0.31920088 0.67296452 0.31920088 ... 0.26202562 0.30167372 0.74633885]
 [0.63920299 0.31920088 0.67296452 ... 0.9452932  0.26202562 0.30167372]
 ...
 [0.30167372 0.26202562 0.9452932  ... 0.67296452 0.31920088 0.63920299]
 [0.74633885 0.30167372 0.26202562 ... 0.31920088 0.67296452 0.31920088]
 [0.95003145 0.74633885 0.30167372 ... 0.63920299 0.31920088 0.67296452]]


Exercise 9.1: Matrix operations

Calculate A + A, AA>, A>A and AB. Write a function that computes A(B − λI) for any λ.

In [23]:
def computation(A,B,arg) :
    return np.dot(A, B-np.dot(arg, np.eye(np.size(B,0),np.size(B,1))))

addA = A + A
print("A + A = " , addA)

A_A_T = np.dot(A,A.T)
print("A_A_T = " ,A_A_T)

A_T_A = np.dot(A.T,A)
print("A_T_A = " ,A_T_A)

AB = np.dot(A,B)
print("AB = ",AB)

arg = float(input("Enter λ "))
print(computation(A,B,arg))

A + A =  [[ 1.19440748 -1.69978103  2.77352906 ... -2.73993103 -0.95053746
  -2.03840953]
 [-3.93804076  4.07577986  1.03319109 ... -4.04915174 -0.80439837
  -3.01626124]
 [-0.47695176  0.46711141 -1.56038544 ... -2.35938625  0.08113354
  -0.69286103]
 ...
 [ 2.28492904 -0.20045866 -1.33999387 ...  1.46766813  2.89020731
  -0.25676671]
 [ 1.99294876 -0.70013232  0.1162251  ...  1.64194822 -2.4926868
  -1.84232113]
 [ 1.53806627 -0.97043432  1.0722608  ... -3.87725337 -1.71724565
   0.67772972]]
A_A_T =  [[477.68350117 -31.33666998  29.5050051  ... -11.40935556   1.5306577
   -4.67650661]
 [-31.33666998 502.42269174  13.74330411 ...   4.08280018   6.26642825
   23.34704793]
 [ 29.5050051   13.74330411 477.09536797 ...  51.13423121   8.49200579
   59.12984939]
 ...
 [-11.40935556   4.08280018  51.13423121 ... 509.56483415  -5.93368008
  -50.84692645]
 [  1.5306577    6.26642825   8.49200579 ...  -5.93368008 471.79841864
   12.31224153]
 [ -4.67650661  23.34704793  59.12984939 ... -50.846

Exercise 9.2: Solving a linear system

Generate a vector b with m entries and solve Bx = b

In [28]:
b = np.random.random(500)
res = np.linalg.solve(B, b)
print("B * x = b" ,res)
np.allclose(np.dot(B, res), b)

B * x = b [-9.94688044e-01 -6.45179239e-01 -5.61311277e-01 -1.21081908e-01
  8.96743420e-01 -1.14426110e+00 -1.55837874e+00 -9.75961328e-02
  8.95522018e-01  1.53800846e-01  4.91425045e-01  4.72562650e-01
 -2.94610818e-01 -3.14596968e-01 -2.56549682e-01  1.16144645e+00
  8.59786541e-01  6.63325313e-01  1.21732999e+00 -2.12517761e-02
 -1.54357247e-01 -3.89512804e-02  7.63228458e-02 -9.99189946e-01
 -9.57432278e-01  2.30464845e-01  8.00012984e-01 -6.06764328e-01
 -9.34852112e-01 -4.46873826e-01 -1.46871531e-01  2.40015745e-02
 -1.64680514e-01 -8.27896613e-01 -7.63184680e-01 -7.20806636e-01
 -3.39661236e-01  3.78291205e-01  4.76093909e-02 -6.07778779e-01
 -3.42863917e-01 -6.84350726e-01  1.49512783e-01  1.13149049e+00
  9.74800328e-01  7.69531447e-02  5.09539940e-01  6.96956176e-02
  5.37673853e-02  6.75023298e-01  5.40844749e-01  7.49994289e-01
 -1.37246168e-01 -3.92403261e-01  6.10231441e-01  2.59764609e-01
 -2.55772888e-01 -3.45788039e-01 -1.49980354e+00 -2.55607235e+00
 -1.64477417e+0

True

Exercise 9.3: Norms
    
Compute the Frobenius norm of A: ||A||F and the infinity norm of B: ||B||∞. Also find the largest and
smallest singular values of B.


In [31]:
x = np.linalg.norm(A, ord ='fro')
print("Frobenius norm of A: ", x)
y = np.linalg.norm(B, ord = np.inf)
print("Infinity form of B: ",y)
smallest = min(np.linalg.svd(B,True,False))
print("Smallest singular value of B: ",smallest)
largest = max(np.linalg.svd(B,True,False))
print("Largest singular value of B: ",largest)

Frobenius norm of A:  316.0479085440001
Infinity form of B:  264.1497376162124
Smallest singular value of B:  0.019897509318724846
Largest singular value of B:  258.9622462749295


Exercise 9.4: Power iteration
    
Generate a matrix Z, n × n, with Gaussian entries, and use the power iteration to find the largest
eigenvalue and corresponding eigenvector of Z. How many iterations are needed till convergence?
Optional: use the time.clock() method to compare computation time when varying n.

In [38]:
import time

Z = np.random.normal(0,1,(200,200))
print(time.process_time())
v,u = np.linalg.eig(Z)
print(time.process_time())

print("Largest Eigenvalue: ", v.max())
print("The Eigenvector: ", u)

16.0
16.09375
Largest Eigenvalue:  (15.463413298505175+0j)
The Eigenvector:  [[ 0.03489206+0.j          0.0517852 -0.04974481j  0.0517852 +0.04974481j
  ... -0.08672004+0.04398538j -0.08672004-0.04398538j
  -0.02010641+0.j        ]
 [-0.01476868+0.j          0.00225324-0.06771043j  0.00225324+0.06771043j
  ...  0.15428333-0.03497725j  0.15428333+0.03497725j
  -0.21080271+0.j        ]
 [-0.09698662+0.j         -0.0343191 +0.01398017j -0.0343191 -0.01398017j
  ...  0.12478993+0.02399942j  0.12478993-0.02399942j
  -0.07305088+0.j        ]
 ...
 [ 0.11237078+0.j         -0.10212596-0.02130178j -0.10212596+0.02130178j
  ... -0.00103445+0.00320477j -0.00103445-0.00320477j
   0.03166122+0.j        ]
 [ 0.02522426+0.j         -0.02069122+0.0126047j  -0.02069122-0.0126047j
  ... -0.02265515+0.00672206j -0.02265515-0.00672206j
   0.06576195+0.j        ]
 [ 0.00416937+0.j         -0.02183242+0.00933965j -0.02183242-0.00933965j
  ...  0.04535713+0.02351972j  0.04535713-0.02351972j
  -0.02035937+0.

Exercise 9.6: Nearest neighbor
    
Write a function that takes a value z and an array A and finds the element in A that is closest to z. The
function should return the closest value, not index.
Hint: Use the built-in functionality of Numpy rather than writing code to find this value manually. In
particular, use brackets and argmin.


In [44]:
def nearest_neighbor(z,A) :
    return A[np.fabs(A - z).argmin()]
A = np.random.random(10) * 10
print(nearest_neighbor(3,A))

3.182823761680017
